# Generated by Django 4.1.3 on 2022-12-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLadyEstetic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='fecha',
        ),
    ]
